[package]
name = "minifb_test"
version = "0.1.0"
authors = ["Mathieu Demange <contact@mathieudemange.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.11.2"